

- name: Copy testing files to arc frontend
  copy: 
    src: files/testing
    dest: "{{ submit_user.home }}"
    directory_mode: 
    owner: "{{ submit_user.user }}"
    group: "{{ submit_user.group }}"

- name: Also copy the cmd template
  template:
    src: templates/submit-cmd.sh.j2
    dest:  "{{ submit_user.home }}/testing/submit-cmd.sh"
    owner: "{{ submit_user.user }}"
    group: "{{ submit_user.group }}"

