- name: Create certificates directory
  file:
    path: "{{ default_user.home }}/certificates"
    state: directory
    owner: "{{ default_user.user }}"
    group: "{{ default_user.group }}"


- name: Create certificate config file
  template: 
    src: templates/x509.cnf
    dest: "{{ default_user.home }}/certificates/{{inventory_hostname}}.cnf"


- name: Create recipe file for creating certificate requeset
  copy:
    dest: "{{ default_user.home }}/certificates/certificate_recipe"
    content: |
     openssl req -new -config {{inventory_hostname}}.cnf -keyout {{inventory_hostname}}.key -out {{inventory_hostname}}.csr
     
     # Go to https://nettskjema.no/a/74868#/page/1 to order the certificate
     # Then copy the cert and key to grid-security folder
     cp *.crt  /etc/grid-security/hostcert.pem
     cp *.key /etc/grid-security/hostkey.pem
