---

#########################################
##    Some preps - PLAY 1
#########################################

- hosts: all
  name: preps
  gather_facts: yes
  become: yes
  tags: prepare

  tasks:



############################################
##    ARC installation and related - PLAY 2
############################################

- hosts: frontend
  name: ARC installation
  gather_facts: yes
  become: yes
  tags: 
    - installarc
    - arc
  tasks:

   - name: Check dependent variables 
     debug: 
       msg: "You have variable site_type different than default: {{site_type}} but not set the runtimedir var. This must be set as site_type different than default will install files in the runtimedir."
     failed_when: runtimedir|length == 0 and site_type != "default"

  roles:
    - role: arc_frontend
      sessionbasename: '/home/sessiondir'
      cachebasename:   '/home/cachedir'
      lrms_bin_path:   '/usr/local/bin'
