---

#########################################
##    Some preps - PLAY 1
#########################################

- hosts: all
  name: preps
  gather_facts: yes
  become: yes
  tags: prepare

  tasks:



############################################
##    ARC installation and related - PLAY 2
############################################

- hosts: frontend
  name: ARC installation
  gather_facts: yes
  become: yes
  tags: 
    - installarc
    - arc
  roles:
    - role: arc_frontend
      sessionbasename: '/home/sessiondir'
      cachebasename:   '/home/cachedir'
      lrms_bin_path:   '/usr/local/bin'
