---

- hosts: all
  name: ARC installation
  become: yes
  tags: 
    - installarc
    - arc
  roles:
    - role: arc_frontend
      sessionbasename: '/mnt/grid/sessiondir'
      cachebasename:   '/mnt/grid/cachedir'
      lrms:            'slurm'
