---

- hosts: all
  name: ARC installation
  gather_facts: yes
  become: yes
  tags: 
    - installarc
    - arc
  roles:
    - role: arc_frontend
      sessionbasename: '/mnt/grid/sessiondir'
      cachebasename:   '/mnt/grid/cachedir'
