- name: Clear cache
  command: yum clean all
  when: ansible_os_family == "RedHat"

    
- name: Set timezone to Europe/Oslo
  community.general.timezone:
    name: "{{timezone}}"


- name: Install emacs, wget, development tools, epel-release  rhel
  package:
    name: ['emacs', 'wget', '@Development tools', 'epel-release', 'time']
    disablerepo: "nordugrid*"
    state: present
  when: (ansible_os_family == "RedHat") 
  ignore_errors: yes


- name: Install chrony, dnf-automatic (rhel 9)
  package:
    name: ['chrony','dnf-automatic']
    state: present
    disablerepo: "nordugrid*"	
  when: (ansible_os_family == "RedHat")  and ansible_distribution_major_version|int == 9


- name: Install ntp, yum-cron (rhel 7)
  package:
    name: ['ntp','yum-cron']
    disablerepo: "nordugrid*"
    state: present
  when: (ansible_os_family == "RedHat")  and ansible_distribution_major_version|int == 7 


- name: Start and enable chronyd, dnf-automatic (el8/9)
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  when: (ansible_os_family == "RedHat")  and ansible_distribution_major_version|int > 7
  with_items:
    - chronyd
    - dnf-automatic.timer


- name: Update system if deb
  shell: apt-get update -y
  when:
    - ansible_os_family == "Debian"


- name: Install emacs, wget, ntp, gpg (deb)
  package:
    name: ['emacs', 'wget', 'ntp','unattended-upgrades', 'gpg', 'time']
    state: present
  when:
    - ansible_os_family == "Debian"
    - ansible_distribution_major_version|int == 11



- name: Start and enable unattended-upgrades (debian)
  systemd:
    name: unattended-upgrades
    enabled: yes
    state: started
  when: 
    - ansible_os_family == "Debian"
    - ansible_distribution_major_version|int == 11
 

- name: Start ntp (debian)
  systemd:
    name: ntp
    enabled: yes
    state: started
  when:
    - ansible_os_family == "Debian"
    - ansible_distribution_major_version|int == 11



