
# Example values
# - localdomain
# - example.com
domain: "localdomain"

# Example values
# - slurm
# - arcuser
# Note: the user must exists on all nodes of the cluster
submit_user:
   user: "arcuser"
   group: "arcuser"
   home: "/home/arcuser"

############################
## ARC
############################
{% if ansible_distribution == "RedHat" %} 
nordugrid_release_v: "6.1"

{% if  ansible_distribution_major_version|int == 7%}
nordugrid_os_v: "el7"
{% else %}
nordugrid_os_v: ansible_distribution_major_version|int
     
{% if  ansible_distribution_release|lower == almalinux or ansible_distribution_release|lower == rocky %}
nordugrid_os_dir: "rocky"
{% elif ansible_distribution_release|lower == Stream %}
nordugrid_os_dir: "centos-stream"
{% else %}
nordugrid_os_dir: "centos"
{% endif %}
{% endif %}	   

{% elif ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"%}
nordugrid_release_v: "6.2"
nordugrid_os_dir: ansible_distribution|lower
nordugrid_os_v: ansible_distribution_major_version|int
nordugrid_os_vname: ansible_distribution_release|lower
{% endif %}


# Example values
# - default (non-wlcg site)
# - atlas (wlcg-site)
site_type: "default"

arc_branch: "next"
use_repo: "nordugrid-testing"

# Example values
# - yes
# - no
remotedelivery: "no"
scratchdir: ""

# Example values
# - fork - simple forking of jobs to the same node as the server
# - sge - (Sun/Oracle) Grid Engine
# - condor - Condor
# - pbs - PBS (covers Torque and other old PBS flavours e.g. OpenPBS, older PBSPro, etc)
# - pbspro - Altair PBS Professional
# - lsf - LSF
# - ll - LoadLeveler
# - slurm - SLURM
# - boinc - Boinc
# See: https://www.nordugrid.org/arc/arc7/admins/reference.html#lrms
lrms: "slurm"

# Example values
# - ""
# - /arc/control
controldir: ""

# Example values
# - /grid/sessiondir
# Note: folder must be available in all nodes (e.g. NFS mounted)
sessionbasename: "{{ submit_user.home }}/sessiondir"

# Example values
# - /grid/cachedir
# Note: folder must be available in all nodes (e.g. NFS mounted)
cachebasename: "{{ submit_user.home }}/cachedir"

# Example values
# - ""
# - /arc/runtime
runtimedir: ""

# See
# https://www.nordugrid.org/arc/arc7/admins/reference.html#queue-name-block
queues: 
  - debug

##  Can be left empty if no accounting will be set up (advanced)
hepspec: "" 
